spring:
  application:
    name: "tag-dsg-poc"
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

---
spring:
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:6432/tag
    username: tag
    password: tag
  liquibase:
    url: jdbc:postgresql://localhost:6432/tag
    user: tag
    password: tag
